// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API.models;

namespace WEB_API.Migrations
{
    [DbContext(typeof(reasondetailcnt))]
    [Migration("20200816090526_newreason")]
    partial class newreason
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEB_API.models.reasondetail", b =>
                {
                    b.Property<int>("id1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("enddate2")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("process2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("reason2")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("startdate2")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("id1");

                    b.ToTable("reasondetails");
                });
#pragma warning restore 612, 618
        }
    }
}
